[[Dbus]]
arch = "aarch64"
git-tree-sha1 = "3e853c628829abbe0fa19181e1b96f5996429392"
libc = "glibc"
os = "linux"

    [[Dbus.download]]
    sha256 = "476db28a41fc160a3000c13c833aa7d614cbde5bd30282d365d4cc2a3a7b6009"
    url = "https://github.com/JuliaBinaryWrappers/Dbus_jll.jl/releases/download/Dbus-v1.14.10+0/Dbus.v1.14.10.aarch64-linux-gnu.tar.gz"
[[Dbus]]
arch = "aarch64"
git-tree-sha1 = "9ea4d384b8efa9dc76ecee36f5d0badcbba2ec8c"
libc = "musl"
os = "linux"

    [[Dbus.download]]
    sha256 = "ae584d97cc8244cd63b9ab33149ddd7caeca6acfe6937361580e15dc08bee4cd"
    url = "https://github.com/JuliaBinaryWrappers/Dbus_jll.jl/releases/download/Dbus-v1.14.10+0/Dbus.v1.14.10.aarch64-linux-musl.tar.gz"
[[Dbus]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "387e744b5c4f9b9ee1c8f32df8995326aa6bd584"
libc = "glibc"
os = "linux"

    [[Dbus.download]]
    sha256 = "eeecc74c03634c3a6f27cf4a0b3d11b9f4db62d94b82d835b3e8e67c81f842f3"
    url = "https://github.com/JuliaBinaryWrappers/Dbus_jll.jl/releases/download/Dbus-v1.14.10+0/Dbus.v1.14.10.armv6l-linux-gnueabihf.tar.gz"
[[Dbus]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "dee43bd3562bafcfa0872cbff30e8b77e57de3e8"
libc = "musl"
os = "linux"

    [[Dbus.download]]
    sha256 = "721b70462bbeb768df3b711752c0c1dcebf46f1776df42350395e7bc91e9ecf7"
    url = "https://github.com/JuliaBinaryWrappers/Dbus_jll.jl/releases/download/Dbus-v1.14.10+0/Dbus.v1.14.10.armv6l-linux-musleabihf.tar.gz"
[[Dbus]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "a8eb7fb4b5f95a885416d5b5ad4bbebdae9d747c"
libc = "glibc"
os = "linux"

    [[Dbus.download]]
    sha256 = "d2d44c6ec9ae160ac8241b862cd60e8fb50a10aeac459acc7d6cf1156067f9d1"
    url = "https://github.com/JuliaBinaryWrappers/Dbus_jll.jl/releases/download/Dbus-v1.14.10+0/Dbus.v1.14.10.armv7l-linux-gnueabihf.tar.gz"
[[Dbus]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "44b16b0e78cce778b61515bf9aca3eb14448f581"
libc = "musl"
os = "linux"

    [[Dbus.download]]
    sha256 = "8f051330e2c519958919c7df353968d1a66b46d4b511acd88d1f413c6463a1ce"
    url = "https://github.com/JuliaBinaryWrappers/Dbus_jll.jl/releases/download/Dbus-v1.14.10+0/Dbus.v1.14.10.armv7l-linux-musleabihf.tar.gz"
[[Dbus]]
arch = "i686"
git-tree-sha1 = "bb642430770664037bb772b817580aef335b030d"
libc = "glibc"
os = "linux"

    [[Dbus.download]]
    sha256 = "0cc090540d5b7db117d5de7193dbe710939eef0eacfbe8318a4d6eeb265d46b3"
    url = "https://github.com/JuliaBinaryWrappers/Dbus_jll.jl/releases/download/Dbus-v1.14.10+0/Dbus.v1.14.10.i686-linux-gnu.tar.gz"
[[Dbus]]
arch = "i686"
git-tree-sha1 = "8198f2f92deec23b391d8edae13cf3713b962edc"
libc = "musl"
os = "linux"

    [[Dbus.download]]
    sha256 = "750dff007cc4f9a47819721785010407dbf48a80c4c20d79a0f6d144d44b700d"
    url = "https://github.com/JuliaBinaryWrappers/Dbus_jll.jl/releases/download/Dbus-v1.14.10+0/Dbus.v1.14.10.i686-linux-musl.tar.gz"
[[Dbus]]
arch = "powerpc64le"
git-tree-sha1 = "8e5cfb96752613e68963f7fd482941ab3e755f0f"
libc = "glibc"
os = "linux"

    [[Dbus.download]]
    sha256 = "fa5c5bda428a9e83ad1d845620ce69b2960aea0558e552e398cb2831dd84f6d1"
    url = "https://github.com/JuliaBinaryWrappers/Dbus_jll.jl/releases/download/Dbus-v1.14.10+0/Dbus.v1.14.10.powerpc64le-linux-gnu.tar.gz"
[[Dbus]]
arch = "x86_64"
git-tree-sha1 = "951960aa7e4599865406f432151003dd82cde65d"
libc = "glibc"
os = "linux"

    [[Dbus.download]]
    sha256 = "137561127633486b167804b8e84aa88d7bbc241e30863bc2dbfc657cbd2a2bd7"
    url = "https://github.com/JuliaBinaryWrappers/Dbus_jll.jl/releases/download/Dbus-v1.14.10+0/Dbus.v1.14.10.x86_64-linux-gnu.tar.gz"
[[Dbus]]
arch = "x86_64"
git-tree-sha1 = "2a35d7d70a3793520d5b430bcefba09b4ccb5875"
libc = "musl"
os = "linux"

    [[Dbus.download]]
    sha256 = "e2a36d0e46976211bd1970af5f79e6ff0ffb9cf82f0a4aa9d0ae8a14c8bb8d69"
    url = "https://github.com/JuliaBinaryWrappers/Dbus_jll.jl/releases/download/Dbus-v1.14.10+0/Dbus.v1.14.10.x86_64-linux-musl.tar.gz"
[[Dbus]]
arch = "x86_64"
git-tree-sha1 = "612b6b2a310a98967b7351cb4ac7f618f82c897c"
os = "freebsd"

    [[Dbus.download]]
    sha256 = "ef50bb273d8702520e5023af37b630ed598537aa11f740b08b4d317cca7dc555"
    url = "https://github.com/JuliaBinaryWrappers/Dbus_jll.jl/releases/download/Dbus-v1.14.10+0/Dbus.v1.14.10.x86_64-unknown-freebsd.tar.gz"
