[[Dbus]]
arch = "aarch64"
git-tree-sha1 = "75c859a3e2b91ecb0f4ff0abff05b9e66f12d57c"
libc = "glibc"
os = "linux"

    [[Dbus.download]]
    sha256 = "e3e23503aee25273d776bbed91b469c76d73cffbca1ff735b9183314e336297a"
    url = "https://github.com/JuliaBinaryWrappers/Dbus_jll.jl/releases/download/Dbus-v1.12.16+1/Dbus.v1.12.16.aarch64-linux-gnu.tar.gz"
[[Dbus]]
arch = "aarch64"
git-tree-sha1 = "e75ec3bf15e09312c6ee3a7e644a474e7dcb9832"
libc = "musl"
os = "linux"

    [[Dbus.download]]
    sha256 = "ba5db0154b508d4351f172c352c0c158e6777870bc57ed25029934bfd0330847"
    url = "https://github.com/JuliaBinaryWrappers/Dbus_jll.jl/releases/download/Dbus-v1.12.16+1/Dbus.v1.12.16.aarch64-linux-musl.tar.gz"
[[Dbus]]
arch = "armv7l"
git-tree-sha1 = "457d2eeb8c0c25d8eb87fa4421c58f4d97327cb0"
libc = "glibc"
os = "linux"

    [[Dbus.download]]
    sha256 = "9739008d83ac8258f136a86c74f9a54166c228c790ecf7587d8a28f4fc7cba70"
    url = "https://github.com/JuliaBinaryWrappers/Dbus_jll.jl/releases/download/Dbus-v1.12.16+1/Dbus.v1.12.16.armv7l-linux-gnueabihf.tar.gz"
[[Dbus]]
arch = "armv7l"
git-tree-sha1 = "9f8b078bb607d6f7319e6f68862ac8300395e73e"
libc = "musl"
os = "linux"

    [[Dbus.download]]
    sha256 = "b0f23439526ccc838e20843a3ee1dc6262f31be060faf58de58195a505fe7970"
    url = "https://github.com/JuliaBinaryWrappers/Dbus_jll.jl/releases/download/Dbus-v1.12.16+1/Dbus.v1.12.16.armv7l-linux-musleabihf.tar.gz"
[[Dbus]]
arch = "i686"
git-tree-sha1 = "4eb455b5fad0043205884d2fc61f3c9cdd3720c2"
libc = "glibc"
os = "linux"

    [[Dbus.download]]
    sha256 = "9312a6c5ba6eb238ea77f0fd1254b23f6bade179104928bda62bf97455f18a81"
    url = "https://github.com/JuliaBinaryWrappers/Dbus_jll.jl/releases/download/Dbus-v1.12.16+1/Dbus.v1.12.16.i686-linux-gnu.tar.gz"
[[Dbus]]
arch = "i686"
git-tree-sha1 = "d245f7a64363fcc05da7cab2b041e84bb15c896d"
libc = "musl"
os = "linux"

    [[Dbus.download]]
    sha256 = "c863c5e48ce1321b91e0874860fd47eb122b9facb52cbde12c53a98dd1d63dcf"
    url = "https://github.com/JuliaBinaryWrappers/Dbus_jll.jl/releases/download/Dbus-v1.12.16+1/Dbus.v1.12.16.i686-linux-musl.tar.gz"
[[Dbus]]
arch = "powerpc64le"
git-tree-sha1 = "6603f73e48fd610e9d1eed78b4a438d8b1194a8c"
libc = "glibc"
os = "linux"

    [[Dbus.download]]
    sha256 = "945f71c3fa4905811c3afe0fa92cd74a5c22d68060ac19f6db9a01ae7224700c"
    url = "https://github.com/JuliaBinaryWrappers/Dbus_jll.jl/releases/download/Dbus-v1.12.16+1/Dbus.v1.12.16.powerpc64le-linux-gnu.tar.gz"
[[Dbus]]
arch = "x86_64"
git-tree-sha1 = "995748afe979c89aa5fb1bf4b696d18cf58f4f6e"
libc = "glibc"
os = "linux"

    [[Dbus.download]]
    sha256 = "557631ae3a31275a70aeed428b31f33da24422d232c6eccacb5a5e7ced6d9cc1"
    url = "https://github.com/JuliaBinaryWrappers/Dbus_jll.jl/releases/download/Dbus-v1.12.16+1/Dbus.v1.12.16.x86_64-linux-gnu.tar.gz"
[[Dbus]]
arch = "x86_64"
git-tree-sha1 = "bef3daae8745ad99407c5b3bc04b5d4378fa5673"
libc = "musl"
os = "linux"

    [[Dbus.download]]
    sha256 = "7e36542c41181cf97061d74212ec7de7c1d27dcbae1746164c848e9668da0dac"
    url = "https://github.com/JuliaBinaryWrappers/Dbus_jll.jl/releases/download/Dbus-v1.12.16+1/Dbus.v1.12.16.x86_64-linux-musl.tar.gz"
[[Dbus]]
arch = "x86_64"
git-tree-sha1 = "052075dbc4cfd38f04bbbca9ce09138755477e09"
os = "freebsd"

    [[Dbus.download]]
    sha256 = "955b5f1f3285d108521f8400a0f568e85f954d865d0be54669de21ad398749ab"
    url = "https://github.com/JuliaBinaryWrappers/Dbus_jll.jl/releases/download/Dbus-v1.12.16+1/Dbus.v1.12.16.x86_64-unknown-freebsd11.1.tar.gz"
